---
- name: Flannel | Enable bridged IPv4 traffic
  shell: |
    sudo sysctl net.bridge.bridge-nf-call-iptables=1

- name: Flannel | Download flannel yaml
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /root/kube-flannel.yml
    mode: 0644

- name: Flannel | Select Flannel networking option
  replace:
    path: /root/kube-flannel.yml
    regexp: 'vxlan'
    replace: 'host-gw'
    backup: yes
  when: FLANNEL_MODE == "host-gw"

- name: Flannel | Apply flannel yaml
  shell: |
    kubectl apply -f /root/kube-flannel.yml

- name: Flannel | Download node-selector-patch.yml
  get_url:
    url: https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/flannel/l2bridge/manifests/node-selector-patch.yml
    dest: /root/node-selector-patch.yml
    mode: 0644

- name: Flannel | Apply NodeSelector to kube-flannel-ds
  shell: |
    kubectl patch ds/kube-flannel-ds-amd64 --patch "$(cat /root/node-selector-patch.yml)" -n=kube-system
