---
- name: Docker | Reload systemd
  shell: systemctl daemon-reload

- name: Docker | Reload docker.socket
  service:
    name: docker.socket
    state: restarted

- name: Docker | Reload docker
  service:
    name: docker
    state: restarted

- name: Docker | Pause while Docker restarts
  pause:
    seconds: 10
    prompt: "Waiting for docker restart"

- name: Docker | Wait for docker
  command: "{{ docker_bin_dir }}/docker images"
  register: docker_ready
  retries: 10
  delay: 5
  until: docker_ready.rc == 0
