- name: Flannel | Download kubernetes hns.psm1
  win_get_url:
    url: "{{ download_links.download_kubernetes_hns }}"
    dest: "{{ download_dest.hns }}"

- name: Flannel | Download InstallImages.ps1
  win_get_url:
    url: "{{ download_links.download_kubernetes_install_images }}"
    dest: "{{ download_dest.install_images }}"

- name: Flannel | Download Dockerfile
  win_get_url:
    url: "{{ download_links.download_kubernetes_dockerfile }}"
    dest: "{{ download_dest.dockerfile }}"

- name: Flannel | Download stop.ps1
  win_get_url:
    url: "{{ download_links.download_kubernetes_stop }}"
    dest: "{{ download_dest.stop }}"

- name: Flannel | Download start-Kubelet.ps1
  win_get_url:
    url: "{{ download_links.download_kubernetes_start_kubelet }}"
    dest: "{{ download_dest.start_kubelet }}"

- name: Flannel | Download start-Kubeproxy.ps1
  win_get_url:
    url: "{{ download_links.download_kubernetes_start_kubeproxy }}"
    dest: "{{ download_dest.start_kubeproxy }}"
