- name: Flannel | Download CNI Flannel
  win_get_url:
    url: "{{ download_links.download_cni_flannel }}"
    dest: "{{ download_dest.cni_flannel }}"

- name: Flannel | Download CNI win-bridge
  win_get_url:
    url: "{{ download_links.download_cni_win_bridge }}"
    dest: "{{ download_dest.cni_win_bridge }}"

- name: Flannel | Download CNI host-local
  win_get_url:
    url: "{{ download_links.download_cni_host_local }}"
    dest: "{{ download_dest.cni_host_local }}"

- name: Flannel | Download net-conf
  win_get_url:
    url: "{{ download_links.download_net_conf }}"
    dest: "{{ download_dest.net_conf }}"

