---
- name: Kubernetes | Create kubernetes dir
  win_file:
    path: "{{ download_info.install_path }}"
    state: directory

- name: Kubernetes | Get kubernetes binaries
  win_copy:
    src: "{{ansible_tmp_dir}}/{{item}}"
    dest: "{{ download_info.install_path }}/{{item}}"
  with_items:
    - kubectl.exe
    - kubelet.exe
    - kube-proxy.exe

- name: Kubelet | Delete kubeconfig
  win_file:
    path: "{{ install_path }}/kubeconfig.yaml"
    state: absent

- name: Kubelet | Create kubeconfig
  win_lineinfile:
    path: "{{ install_path }}/kubeconfig.yaml"
    create: yes
    line: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: local
        cluster:
          server: http://{{ kubernetes_info.MASTER_IP }}:8080
      users:
      - name: kubelet
      contexts:
      - context:
          cluster: local
          user: kubelet
        name: kubelet-context
      current-context: kubelet-context
    newline: unix

- name: Kubelet | Set kubectl context
  win_shell: |
    $ErrorActionPreference = "Stop"
    {{ install_path }}\\kubectl.exe config set-cluster default-cluster --server={{ kubernetes_info.MASTER_IP }}:8080
    if($LASTEXITCODE) {
        Throw "Failed to run kubectl.exe config set-cluster"
    }
    {{ install_path }}\\kubectl.exe config set-context local --cluster=default-cluster --user=default-admin
    if($LASTEXITCODE) {
        Throw "Failed to run kubectl.exe config set-context"
    }
    {{ install_path }}\\kubectl.exe config use-context local
    if($LASTEXITCODE) {
        Throw "Failed to run kubectl.exe config use-context"
    }
